// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://duvmpbqeqjlbnpnaxnsb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImR1dm1wYnFlcWpsYm5wbmF4bnNiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMwNTM4NTEsImV4cCI6MjA2ODYyOTg1MX0.EwB-XJ4hAUCoObKwbHpI_zX5fuFODuCT4wLHqaOEZRY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});